### ISSUE TITLE
Only replace /browser for GitHub repositories

### ISSUE THREAD

**Issue by ryandesign** [trac-hacks/trac-github#107]
It's my understanding that trac-github replaces the /browser portion of the Trac system with a redirect to the GitHub repository browser.

It is possible to configure Trac with multiple repositories. One could have a GitHub repository, and also a Subversion repository.

Is it possible to configure trac-github so that links to the GitHub repository are redirected to the GitHub repository browser, while links to the Subversion repository continue to be served by the Trac browser? If so, how? If not, please make that possible.

**Comment by raimue** [comment]
This should be about /changeset instead of /browser, which is not changed by this plugin. The recommended configuration example disables BrowserModule, but it is not a strict requirement. The class name GitHubBrowser is a bit misleading as it is a replacement for ChangesetModule and only works on /changeset.

**Comment by ryandesign** [comment]
Thanks so much!
