### ISSUE TITLE
Possible new feature - selective behaviour on branches

### ISSUE THREAD

**Issue by ajj** [trac-hacks/trac-github#108]
Hi

trac-github is working well for me, but I was wondering whether the possibility of having selective behaviour for branches had been considered?

For example, I would like references to tickets to be possible on branches, but fixes/closes to only apply to master. This way tickets won't be closed until pull requests are complete.

**Comment by aaugustin** [comment]
I don't remember seeing a ticket or PR about this. The idea makes sense.

**Comment by neverpanic** [comment]
Wouldn't this be a feature that should be implemented in [Trac's CommitTicketUpdater](https://trac.edgewall.org/wiki/CommitTicketUpdater), not in trac-github? trac-github does not add notifications to tickets, it just syncs commits.

**Comment by aaugustin** [comment]
Indeed, @neverpanic is right.

**Comment by rjollos** [comment]
I was thinking similarly, that this feature should probably be implemented by Trac. [#10905](https://trac.edgewall.org/ticket/10905) is related, requesting to enable CommitTicketUpdater for only some repositories. It might be possible to create a more generalized solution so that CommitTicketUpdater is only enabled (or is disabled) for paths matching a regex. The [TracLinks](https://trac.edgewall.org/wiki/TracLinks#VersionControlrelatedlinks) syntax could be followed in including the repository name in the path.

**Comment by neverpanic** [comment]
This is a problem we'll also try to solve for MacPorts. Our current idea is to make the [`ticket_prefix`](https://trac.edgewall.org/browser/trunk/tracopt/ticket/commit_updater.py?rev=14481&marks=140#L130) variable configurable so that we can ignore `#123`, which is claimed by GitHub, and replace it with a regex that would match what we use to reference Trac tickets.

**Comment by rjollos** [comment]
[MultiProjectCommitTicketUpdaterPlugin](https://trac-hacks.org/wiki/MultiProjectCommitTicketUpdaterPlugin) does something like that.

The jQuery UI project seems to use `gh-123` to reference [GitHub tickets](https://github.com/jquery/jquery-ui/commit/f1fa076f62e99089257f6f8159cb2ce503f0abc2). I'm not sure how that is configured.
