### ISSUE TITLE
No handler matched request to /github after installing the plugin

### ISSUE THREAD

**Issue by jlehikoi** [trac-hacks/trac-github#13]
Hello,

I have been trying to install the trac-github plugin, but I keep running into the "No handler matched request to /github" when trying to access the /github -page on our trac.

I am using Trac 1.0.1. The trac is installed on a virtual machine, and it is being accessed via HTTPS at a non-standard port (the virtual machine has a redirect from 443 to our chosen port). I am trying to integrate Trac with a private github repo.

I have completed the steps laid out in the Setup section of the readme file. I have set up a mirror of our github repository on the same machine as Trac. I have also set up SSH key access for the www-data user to this repository. I have verified that the access works. 

Here is the relevant part of my trac.ini
https://gist.github.com/jlehikoi/18c1a4c2e0762569d9bb

The gist also includes trac.log after restarting apache and sending the test payload from Github. The only warning in the log file is the 404 error on line 65. When I point my browser to /github, I get the "No handler matched request to /github" error. 

Could this problem be caused by the fact that we use Trac over HTTPS and/or not in port 443? That's the only thing that I can think of, I'm pretty sure I've done the setup otherwise correctly.

**Comment by cdw9** [comment]
@jlehikoi did you ever figure out what the problem was?

I had this plugin working in Trac 0.12, but it stopped working after we upgraded to 1.0. I have followed the instructions multiple times to make sure all the pieces are in place, but it seems the plugin just isn't being loaded. Would be nice if anyone has any new insights.

**Comment by aaugustin** [comment]
Usually this happens because the Python process running Trac cannot import trac-github. This can be hard to debug, even if you're an experienced Python programmer. I'm very sorry that I don't have useful advice to provide, aside from:

- increasing logging verbosity and reviewing logs
- trying to run a Python shell in the same environment as the web server and to `import tracext.github` there

**Comment by jlehikoi** [comment]
@cdw9, unfortunately I don't have the solution (or the documentation) at hand any more, as we switched from Trac to using Github issues. From what I recall, I did get it working eventually. This might have required upgrading/downgrading Trac and/or hacking some Python to fix the issue. Sorry I can't help more.

**Comment by cdw9** [comment]
Thanks for the tips! This did help me move forward.  (After the trac upgrade, I didn't realize it had been installed in a virtualenv, so I just had to make sure trac-github was installed in that virtualenv)

**Comment by aaugustin** [comment]
👍 Glad to hear you figured it out!
